[build]
  # Directory to change to before starting a build
  base = "app/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "app/build"
  
  # Default build command
  command = "npm run build"

# Production context: all deploys from the Production branch
[context.production]
  publish = "app/build"
  command = "npm run build"

# Deploy Preview context: all Deploy Previews
[context.deploy-preview]
  publish = "app/build"
  command = "npm run build"

# Branch Deploy context: all deploys that are not from a pull/merge request
[context.branch-deploy]
  publish = "app/build"
  command = "npm run build"

# Redirect rules for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' http://localhost:5678 https:;"

# Environment variables (set these in Netlify dashboard)
# REACT_APP_N8N_BASE_URL = "http://localhost:5678/webhook/18ea1485-beab-4bca-b320-f3686bc7e611"
# REACT_APP_N8N_API_KEY = "your-api-key"